apiVersion: v1
kind: Service
metadata:
  name: ping-prueba-short-svc
  namespace: default
spec:
  selector:
    app: ping-prueba-short-svc
  ports:
    - protocol: TCP
      port: 30300
      targetPort: 8080